le_voyageur_client_homepage:
    path:     /
    defaults: { _controller: LeVoyageurClientBundle:Default:index }

home:
    path:     /home
    defaults: { _controller: LeVoyageurClientBundle:User:home }

